# -*- coding: utf-8 -*-
"""2Stage_ResNet50ModelOptimalThreshold.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sC2WEVNB5OCrNBBoSqzDSzMu8j1riwHj
"""

# Imports
import os
import random
import shutil
import cv2
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, random_split

from torchvision import datasets, transforms, models

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

import seaborn as sns

#!pip install --upgrade --force-reinstall torch torchvision torchaudio

# Reproducibility and Device

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

# Mount Drive
from google.colab import drive
drive.mount('/content/drive', force_remount=True)



# Original Kaggle dataset path.
# Expected structure:
# chest_xray/
#   train/NORMAL
#   train/PNEUMONIA
#   test/NORMAL
#   test/PNEUMONIA
#   val/NORMAL
#   val/PNEUMONIA

ORIGINAL_DATA_DIR = "/content/drive/MyDrive/finalProject_682/chest_xray"

# Local Colab folders.
BINARY_DATA_DIR = "/content/chest_xray_binary"
SUBTYPE_DATA_DIR = "/content/chest_xray_subtype"
THREE_CLASS_DATA_DIR = "/content/chest_xray_3class"

# If dataset shows up as 0, then run this script to delete created folders
# to allow recreation

# import shutil
# import os

# for path in [BINARY_DATA_DIR, SUBTYPE_DATA_DIR, THREE_CLASS_DATA_DIR]:
#     if os.path.exists(path):
#         shutil.rmtree(path)
#         print("Deleted:", path)

# Dataset Creation

def safe_copy(src, dst):
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    shutil.copy2(src, dst)


def is_image_file(file_name):
    valid_extensions = (".jpg", ".jpeg", ".png", ".bmp", ".tif", ".tiff", ".webp")
    return file_name.lower().endswith(valid_extensions)


def create_two_stage_datasets(original_dir, binary_dir, subtype_dir, three_class_dir):
    """
    Creates:
    1. binary_dir: NORMAL vs PNEUMONIA
    2. subtype_dir: BACTERIAL vs VIRAL
    3. three_class_dir: NORMAL vs BACTERIAL vs VIRAL
    """

    if os.path.exists(binary_dir) and os.path.exists(subtype_dir) and os.path.exists(three_class_dir):
        print("Datasets already exist. Skipping dataset creation.")
        return

    for split in ["train", "val", "test"]:
        original_split_dir = os.path.join(original_dir, split)
        normal_dir = os.path.join(original_split_dir, "NORMAL")
        pneumonia_dir = os.path.join(original_split_dir, "PNEUMONIA")

        for base_dir, classes in [
            (binary_dir, ["NORMAL", "PNEUMONIA"]),
            (subtype_dir, ["BACTERIAL", "VIRAL"]),
            (three_class_dir, ["NORMAL", "BACTERIAL", "VIRAL"]),
        ]:
            for cls in classes:
                os.makedirs(os.path.join(base_dir, split, cls), exist_ok=True)

        # NORMAL images
        if os.path.exists(normal_dir):
            for file_name in os.listdir(normal_dir):
                if not is_image_file(file_name):
                    continue

                src = os.path.join(normal_dir, file_name)
                if not os.path.isfile(src):
                    continue

                safe_copy(src, os.path.join(binary_dir, split, "NORMAL", file_name))
                safe_copy(src, os.path.join(three_class_dir, split, "NORMAL", file_name))

        # PNEUMONIA images
        if os.path.exists(pneumonia_dir):
            for file_name in os.listdir(pneumonia_dir):
                if not is_image_file(file_name):
                    continue

                src = os.path.join(pneumonia_dir, file_name)
                if not os.path.isfile(src):
                    continue

                lower_name = file_name.lower()

                safe_copy(src, os.path.join(binary_dir, split, "PNEUMONIA", file_name))

                if "bacteria" in lower_name:
                    safe_copy(src, os.path.join(subtype_dir, split, "BACTERIAL", file_name))
                    safe_copy(src, os.path.join(three_class_dir, split, "BACTERIAL", file_name))

                elif "virus" in lower_name:
                    safe_copy(src, os.path.join(subtype_dir, split, "VIRAL", file_name))
                    safe_copy(src, os.path.join(three_class_dir, split, "VIRAL", file_name))

                else:
                    print("Skipped unknown pneumonia subtype:", file_name)

    print("Created all datasets.")


def print_folder_counts(data_dir, classes):
    print("\nDataset:", data_dir)
    for split in ["train", "val", "test"]:
        print("\n", split.upper())
        for cls in classes:
            folder = os.path.join(data_dir, split, cls)
            count = len(os.listdir(folder)) if os.path.exists(folder) else 0
            print(f"{cls}: {count}")


create_two_stage_datasets(
    ORIGINAL_DATA_DIR,
    BINARY_DATA_DIR,
    SUBTYPE_DATA_DIR,
    THREE_CLASS_DATA_DIR
)

print_folder_counts(BINARY_DATA_DIR, ["NORMAL", "PNEUMONIA"])
print_folder_counts(SUBTYPE_DATA_DIR, ["BACTERIAL", "VIRAL"])
print_folder_counts(THREE_CLASS_DATA_DIR, ["NORMAL", "BACTERIAL", "VIRAL"])

# Image Transformations

IMG_SIZE = 224
BATCH_SIZE = 32

train_transforms = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.RandomHorizontalFlip(p=0.3),
    transforms.RandomRotation(5),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225])
])

val_test_transforms = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225])
])

# Dataset Loader

def make_loaders(data_dir, batch_size=32, use_train_split_for_validation=True):
    train_dir = os.path.join(data_dir, "train")
    val_dir = os.path.join(data_dir, "val")
    test_dir = os.path.join(data_dir, "test")

    full_train_dataset = datasets.ImageFolder(train_dir, transform=train_transforms)
    class_names = full_train_dataset.classes

    if use_train_split_for_validation:
        val_size = int(0.15 * len(full_train_dataset))
        train_size = len(full_train_dataset) - val_size

        train_dataset, val_dataset = random_split(
            full_train_dataset,
            [train_size, val_size],
            generator=torch.Generator().manual_seed(SEED)
        )

        train_targets_for_weights = np.array(full_train_dataset.targets)
    else:
        train_dataset = full_train_dataset
        val_dataset = datasets.ImageFolder(val_dir, transform=val_test_transforms)
        train_targets_for_weights = np.array(full_train_dataset.targets)

    test_dataset = datasets.ImageFolder(test_dir, transform=val_test_transforms)

    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=2)
    val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False, num_workers=2)
    test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False, num_workers=2)

    num_classes = len(class_names)
    class_counts = np.bincount(train_targets_for_weights, minlength=num_classes)
    class_counts_safe = np.where(class_counts == 0, 1, class_counts)

    class_weights = 1.0 / torch.tensor(class_counts_safe, dtype=torch.float)
    class_weights = class_weights / class_weights.sum()
    class_weights = class_weights.to(device)

    print("\nLoaded:", data_dir)
    print("Classes:", class_names)
    print("Class to index:", datasets.ImageFolder(train_dir).class_to_idx)
    print("Class counts:", dict(zip(class_names, class_counts)))
    print("Class weights:", class_weights)
    print("Train size:", len(train_dataset))
    print("Val size:", len(val_dataset))
    print("Test size:", len(test_dataset))

    return {
        "train_loader": train_loader,
        "val_loader": val_loader,
        "test_loader": test_loader,
        "train_dataset": train_dataset,
        "val_dataset": val_dataset,
        "test_dataset": test_dataset,
        "class_names": class_names,
        "class_weights": class_weights,
        "num_classes": num_classes,
        "class_to_idx": datasets.ImageFolder(train_dir).class_to_idx
    }

# ResNet50 Model
class ResNet50Classifier(nn.Module):
    def __init__(self, num_classes=2, pretrained=True):
        super(ResNet50Classifier, self).__init__()

        weights = models.ResNet50_Weights.IMAGENET1K_V1 if pretrained else None
        base_model = models.resnet50(weights=weights)

        self.conv1 = base_model.conv1
        self.bn1 = base_model.bn1
        self.relu = base_model.relu
        self.maxpool = base_model.maxpool

        self.layer1 = base_model.layer1
        self.layer2 = base_model.layer2
        self.layer3 = base_model.layer3
        self.layer4 = base_model.layer4

        self.avgpool = nn.AdaptiveAvgPool2d((1, 1))
        self.classifier = nn.Sequential(
            nn.Dropout(0.4),
            nn.Linear(2048, num_classes)
        )

    def forward(self, x):
        x = self.conv1(x)
        x = self.bn1(x)
        x = self.relu(x)
        x = self.maxpool(x)

        x = self.layer1(x)
        x = self.layer2(x)
        x = self.layer3(x)
        x = self.layer4(x)

        x = self.avgpool(x)
        x = torch.flatten(x, 1)
        x = self.classifier(x)
        return x

# Training Helpers

def train_one_epoch(model, loader, criterion, optimizer, device):
    model.train()
    running_loss = 0.0
    all_preds = []
    all_labels = []

    for images, labels in loader:
        images = images.to(device)
        labels = labels.to(device)

        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        running_loss += loss.item() * images.size(0)

        _, preds = torch.max(outputs, 1)
        all_preds.extend(preds.detach().cpu().numpy())
        all_labels.extend(labels.detach().cpu().numpy())

    epoch_loss = running_loss / len(loader.dataset)
    epoch_acc = accuracy_score(all_labels, all_preds)
    return epoch_loss, epoch_acc


def evaluate(model, loader, criterion, device):
    model.eval()
    running_loss = 0.0
    all_preds = []
    all_labels = []
    all_probs = []

    with torch.no_grad():
        for images, labels in loader:
            images = images.to(device)
            labels = labels.to(device)

            outputs = model(images)
            loss = criterion(outputs, labels)
            probs = torch.softmax(outputs, dim=1)

            running_loss += loss.item() * images.size(0)

            _, preds = torch.max(outputs, 1)
            all_preds.extend(preds.detach().cpu().numpy())
            all_labels.extend(labels.detach().cpu().numpy())
            all_probs.extend(probs.detach().cpu().numpy())

    epoch_loss = running_loss / len(loader.dataset)
    epoch_acc = accuracy_score(all_labels, all_preds)
    return epoch_loss, epoch_acc, np.array(all_labels), np.array(all_preds), np.array(all_probs)


def freeze_all_except_classifier(model):
    for name, param in model.named_parameters():
        if "classifier" in name:
            param.requires_grad = True
        else:
            param.requires_grad = False


def unfreeze_deep_layers(model):
    for name, param in model.named_parameters():
        if "layer3" in name or "layer4" in name or "classifier" in name:
            param.requires_grad = True
        else:
            param.requires_grad = False


def make_classifier_optimizer(model, lr=1e-4):
    return optim.AdamW(
        model.classifier.parameters(),
        lr=lr,
        weight_decay=1e-4
    )


def make_finetune_optimizer(model):
    return optim.AdamW([
        {"params": model.layer3.parameters(), "lr": 1e-6},
        {"params": model.layer4.parameters(), "lr": 1e-5},
        {"params": model.classifier.parameters(), "lr": 1e-4},
    ], weight_decay=1e-4)


def train_model_phase(model, loaders, optimizer, phase_name, best_path, epochs=5, patience=3):
    criterion = nn.CrossEntropyLoss(weight=loaders["class_weights"])

    scheduler = optim.lr_scheduler.ReduceLROnPlateau(
        optimizer,
        mode="min",
        factor=0.5,
        patience=2
    )

    best_val_loss = float("inf")
    epochs_without_improvement = 0

    history = {
        "train_loss": [],
        "train_acc": [],
        "val_loss": [],
        "val_acc": [],
        "val_f1": []
    }

    for epoch in range(epochs):
        train_loss, train_acc = train_one_epoch(
            model,
            loaders["train_loader"],
            criterion,
            optimizer,
            device
        )

        val_loss, val_acc, y_true_val, y_pred_val, _ = evaluate(
            model,
            loaders["val_loader"],
            criterion,
            device
        )

        val_precision = precision_score(y_true_val, y_pred_val, average="weighted", zero_division=0)
        val_recall = recall_score(y_true_val, y_pred_val, average="weighted", zero_division=0)
        val_f1 = f1_score(y_true_val, y_pred_val, average="weighted", zero_division=0)

        scheduler.step(val_loss)

        history["train_loss"].append(train_loss)
        history["train_acc"].append(train_acc)
        history["val_loss"].append(val_loss)
        history["val_acc"].append(val_acc)
        history["val_f1"].append(val_f1)

        print(f"\n{phase_name} | Epoch [{epoch + 1}/{epochs}]")
        print("=" * 70)
        print(f"Train Loss: {train_loss:.4f} | Train Acc: {train_acc:.4f}")
        print(f"Val   Loss: {val_loss:.4f} | Val   Acc: {val_acc:.4f}")
        print(f"Val Precision: {val_precision:.4f} | Val Recall: {val_recall:.4f} | Val F1: {val_f1:.4f}")

        if val_loss < best_val_loss:
            best_val_loss = val_loss
            epochs_without_improvement = 0
            torch.save(model.state_dict(), best_path)
            print("Saved best model based on validation loss.")
        else:
            epochs_without_improvement += 1

        if epochs_without_improvement >= patience:
            print("Early stopping triggered.")
            break

    model.load_state_dict(torch.load(best_path, map_location=device))
    model.eval()
    return model, history


def train_staged_resnet(loaders, model_name, frozen_epochs=5, finetune_epochs=8):
    model = ResNet50Classifier(num_classes=loaders["num_classes"], pretrained=True).to(device)

    # Phase 1: train only classifier.
    freeze_all_except_classifier(model)
    optimizer = make_classifier_optimizer(model, lr=1e-4)
    frozen_path = f"best_{model_name}_frozen.pth"

    model, history_1 = train_model_phase(
        model=model,
        loaders=loaders,
        optimizer=optimizer,
        phase_name=f"{model_name} Phase 1: Frozen Backbone",
        best_path=frozen_path,
        epochs=frozen_epochs,
        patience=3
    )

    # Phase 2: unfreeze deeper layers with smaller LR.
    unfreeze_deep_layers(model)
    optimizer = make_finetune_optimizer(model)
    finetune_path = f"best_{model_name}_finetuned.pth"

    model, history_2 = train_model_phase(
        model=model,
        loaders=loaders,
        optimizer=optimizer,
        phase_name=f"{model_name} Phase 2: Fine-Tuning",
        best_path=finetune_path,
        epochs=finetune_epochs,
        patience=5
    )

    return model, frozen_path, finetune_path, history_1, history_2


def evaluate_and_print(model, loaders, title):
    criterion = nn.CrossEntropyLoss(weight=loaders["class_weights"])
    test_loss, test_acc, y_true, y_pred, y_probs = evaluate(
        model,
        loaders["test_loader"],
        criterion,
        device
    )

    print(f"\n{title}")
    print("Test Loss:", test_loss)
    print("Test Accuracy:", test_acc)
    print("Precision:", precision_score(y_true, y_pred, average="weighted", zero_division=0))
    print("Recall:", recall_score(y_true, y_pred, average="weighted", zero_division=0))
    print("F1-score:", f1_score(y_true, y_pred, average="weighted", zero_division=0))
    print("\nClassification Report:\n")
    print(classification_report(y_true, y_pred, target_names=loaders["class_names"], zero_division=0))

    cm = confusion_matrix(y_true, y_pred)
    plt.figure(figsize=(6, 5))
    sns.heatmap(
        cm,
        annot=True,
        fmt="d",
        xticklabels=loaders["class_names"],
        yticklabels=loaders["class_names"],
        cmap="Blues"
    )
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.title(title)
    plt.show()

    return y_true, y_pred, y_probs

# Stage 1: NORMAL vs PNEUMONIA

binary_loaders = make_loaders(
    BINARY_DATA_DIR,
    BATCH_SIZE,
    use_train_split_for_validation=True
)

stage1_net, stage1_frozen_path, stage1_finetune_path, stage1_history_1, stage1_history_2 = train_staged_resnet(
    binary_loaders,
    model_name="stage1_normal_vs_pneumonia",
    frozen_epochs=5,
    finetune_epochs=8
)

s1_true, s1_pred, s1_probs = evaluate_and_print(
    stage1_net,
    binary_loaders,
    title="Stage 1: NORMAL vs PNEUMONIA"
)

print("ORIGINAL_DATA_DIR:", ORIGINAL_DATA_DIR)
print("Exists:", os.path.exists(ORIGINAL_DATA_DIR))
print("Contents:", os.listdir(ORIGINAL_DATA_DIR) if os.path.exists(ORIGINAL_DATA_DIR) else "Missing")

# Train Stage 2: BACTERIAL vs VIRAL

subtype_loaders = make_loaders(
    SUBTYPE_DATA_DIR,
    BATCH_SIZE,
    use_train_split_for_validation=True
)

stage2_net, stage2_frozen_path, stage2_finetune_path, stage2_history_1, stage2_history_2 = train_staged_resnet(
    subtype_loaders,
    model_name="stage2_bacterial_vs_viral",
    frozen_epochs=5,
    finetune_epochs=8
)

s2_true, s2_pred, s2_probs = evaluate_and_print(
    stage2_net,
    subtype_loaders,
    title="Stage 2: BACTERIAL vs VIRAL"
)

# Final Two-Stage Evaluation on 3-Class Test Set

three_class_test_dataset = datasets.ImageFolder(
    os.path.join(THREE_CLASS_DATA_DIR, "test"),
    transform=val_test_transforms
)

three_class_test_loader = DataLoader(
    three_class_test_dataset,
    batch_size=1,
    shuffle=False,
    num_workers=2
)

final_class_names = three_class_test_dataset.classes
final_class_to_idx = three_class_test_dataset.class_to_idx
idx_to_final_class = {v: k for k, v in final_class_to_idx.items()}

print("\nFinal 3-class mapping:", final_class_to_idx)
print("Stage 1 mapping:", binary_loaders["class_to_idx"])
print("Stage 2 mapping:", subtype_loaders["class_to_idx"])

stage1_normal_idx = binary_loaders["class_to_idx"]["NORMAL"]
stage1_pneumonia_idx = binary_loaders["class_to_idx"]["PNEUMONIA"]

stage2_bacterial_idx = subtype_loaders["class_to_idx"]["BACTERIAL"]
stage2_viral_idx = subtype_loaders["class_to_idx"]["VIRAL"]

final_normal_idx = final_class_to_idx["NORMAL"]
final_bacterial_idx = final_class_to_idx["BACTERIAL"]
final_viral_idx = final_class_to_idx["VIRAL"]

STAGE1_PNEUMONIA_THRESHOLD = 0.55

def two_stage_predict(image_tensor):
    image_tensor = image_tensor.to(device)

    with torch.no_grad():
        stage1_output = stage1_net(image_tensor)
        stage1_probs = torch.softmax(stage1_output, dim=1).detach().cpu().numpy()[0]

        p_pneumonia = stage1_probs[stage1_pneumonia_idx]

        if p_pneumonia < STAGE1_PNEUMONIA_THRESHOLD:
            return final_normal_idx, stage1_probs, None

        stage2_output = stage2_net(image_tensor)
        stage2_probs = torch.softmax(stage2_output, dim=1).detach().cpu().numpy()[0]
        stage2_pred = int(np.argmax(stage2_probs))

        if stage2_pred == stage2_bacterial_idx:
            return final_bacterial_idx, stage1_probs, stage2_probs
        else:
            return final_viral_idx, stage1_probs, stage2_probs


final_true = []
final_pred = []
final_records = []

for idx, (image, label) in enumerate(three_class_test_loader):
    pred_idx, stage1_probs, stage2_probs = two_stage_predict(image)

    true_idx = int(label.item())
    final_true.append(true_idx)
    final_pred.append(pred_idx)

    final_records.append({
        "index": idx,
        "true": true_idx,
        "pred": pred_idx,
        "true_label": idx_to_final_class[true_idx],
        "pred_label": idx_to_final_class[pred_idx],
        "stage1_probs": stage1_probs,
        "stage2_probs": stage2_probs
    })

final_true = np.array(final_true)
final_pred = np.array(final_pred)

print("\nFinal Two-Stage 3-Class Test Results")
print("Accuracy:", accuracy_score(final_true, final_pred))
print("Precision:", precision_score(final_true, final_pred, average="weighted", zero_division=0))
print("Recall:", recall_score(final_true, final_pred, average="weighted", zero_division=0))
print("F1-score:", f1_score(final_true, final_pred, average="weighted", zero_division=0))
print("\nClassification Report:\n")
print(classification_report(final_true, final_pred, target_names=final_class_names, zero_division=0))

cm = confusion_matrix(final_true, final_pred)
plt.figure(figsize=(7, 6))
sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    xticklabels=final_class_names,
    yticklabels=final_class_names,
    cmap="Blues"
)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Final Two-Stage 3-Class Confusion Matrix")
plt.show()

# Grad-CAM and Grad-CAM++

def denormalize_image(tensor_img):
    img = tensor_img.detach().cpu().numpy().transpose(1, 2, 0)
    mean = np.array([0.485, 0.456, 0.406])
    std = np.array([0.229, 0.224, 0.225])
    img = std * img + mean
    img = np.clip(img, 0, 1)
    return img


def overlay_heatmap(original_img, heatmap, alpha=0.45):
    heatmap_uint8 = np.uint8(255 * heatmap)
    heatmap_color = cv2.applyColorMap(heatmap_uint8, cv2.COLORMAP_JET)
    heatmap_color = cv2.cvtColor(heatmap_color, cv2.COLOR_BGR2RGB)
    heatmap_color = heatmap_color / 255.0
    overlay = alpha * heatmap_color + (1 - alpha) * original_img
    overlay = np.clip(overlay, 0, 1)
    return overlay


class GradCAMBase:
    def __init__(self, model, target_layer):
        self.model = model
        self.target_layer = target_layer
        self.gradients = None
        self.activations = None
        self.forward_handle = None
        self.backward_handle = None
        self._register_hooks()

    def _register_hooks(self):
        def forward_hook(module, input, output):
            self.activations = output

        def backward_hook(module, grad_input, grad_output):
            self.gradients = grad_output[0]

        self.forward_handle = self.target_layer.register_forward_hook(forward_hook)
        self.backward_handle = self.target_layer.register_full_backward_hook(backward_hook)

    def remove_hooks(self):
        self.forward_handle.remove()
        self.backward_handle.remove()

    def forward_backward(self, input_tensor, class_idx=None):
        self.model.zero_grad()
        output = self.model(input_tensor)

        if class_idx is None:
            class_idx = torch.argmax(output, dim=1).item()

        score = output[:, class_idx]
        score.backward(retain_graph=True)
        return output, class_idx


class GradCAM(GradCAMBase):
    def generate(self, input_tensor, class_idx=None):
        output, class_idx = self.forward_backward(input_tensor, class_idx)
        gradients = self.gradients
        activations = self.activations

        weights = torch.mean(gradients, dim=(2, 3), keepdim=True)
        cam = torch.sum(weights * activations, dim=1).squeeze()
        cam = torch.relu(cam)
        cam = cam.detach().cpu().numpy()
        cam = cv2.resize(cam, (input_tensor.shape[3], input_tensor.shape[2]))

        if cam.max() != cam.min():
            cam = (cam - cam.min()) / (cam.max() - cam.min())
        else:
            cam = np.zeros_like(cam)

        return cam, output, class_idx


class GradCAMPlusPlus(GradCAMBase):
    def generate(self, input_tensor, class_idx=None):
        output, class_idx = self.forward_backward(input_tensor, class_idx)
        gradients = self.gradients
        activations = self.activations

        grads_power_2 = gradients ** 2
        grads_power_3 = gradients ** 3
        sum_activations = torch.sum(activations, dim=(2, 3), keepdim=True)

        eps = 1e-8
        alpha_num = grads_power_2
        alpha_denom = 2 * grads_power_2 + sum_activations * grads_power_3
        alpha_denom = torch.where(
            alpha_denom != 0.0,
            alpha_denom,
            torch.ones_like(alpha_denom) * eps
        )
        alphas = alpha_num / (alpha_denom + eps)

        positive_gradients = torch.relu(gradients)
        weights = torch.sum(alphas * positive_gradients, dim=(2, 3), keepdim=True)

        cam = torch.sum(weights * activations, dim=1).squeeze()
        cam = torch.relu(cam)
        cam = cam.detach().cpu().numpy()
        cam = cv2.resize(cam, (input_tensor.shape[3], input_tensor.shape[2]))

        if cam.max() != cam.min():
            cam = (cam - cam.min()) / (cam.max() - cam.min())
        else:
            cam = np.zeros_like(cam)

        return cam, output, class_idx


stage1_gradcam = GradCAM(stage1_net, stage1_net.layer4[-1])
stage1_gradcam_pp = GradCAMPlusPlus(stage1_net, stage1_net.layer4[-1])
stage2_gradcam = GradCAM(stage2_net, stage2_net.layer4[-1])
stage2_gradcam_pp = GradCAMPlusPlus(stage2_net, stage2_net.layer4[-1])

# Two-Stage Grad-CAM Visualization


def visualize_two_stage_explanation(dataset, index=None):
    if index is None:
        index = random.randint(0, len(dataset) - 1)

    image_tensor, true_label = dataset[index]
    input_tensor = image_tensor.unsqueeze(0).to(device)
    original_img = denormalize_image(image_tensor)

    pred_idx, stage1_probs, stage2_probs = two_stage_predict(input_tensor)

    stage1_pred = int(np.argmax(stage1_probs))
    cam1, _, _ = stage1_gradcam.generate(input_tensor, class_idx=stage1_pred)
    cam1_pp, _, _ = stage1_gradcam_pp.generate(input_tensor, class_idx=stage1_pred)

    overlay_cam1 = overlay_heatmap(original_img, cam1)
    overlay_cam1_pp = overlay_heatmap(original_img, cam1_pp)

    if stage2_probs is not None:
        stage2_pred = int(np.argmax(stage2_probs))
        cam2, _, _ = stage2_gradcam.generate(input_tensor, class_idx=stage2_pred)
        cam2_pp, _, _ = stage2_gradcam_pp.generate(input_tensor, class_idx=stage2_pred)
        overlay_cam2 = overlay_heatmap(original_img, cam2)
        overlay_cam2_pp = overlay_heatmap(original_img, cam2_pp)
    else:
        overlay_cam2 = None
        overlay_cam2_pp = None

    plt.figure(figsize=(20, 8))

    plt.subplot(2, 3, 1)
    plt.imshow(original_img)
    plt.title(
        f"Original\nTrue: {idx_to_final_class[int(true_label)]}\n"
        f"Final Pred: {idx_to_final_class[pred_idx]}"
    )
    plt.axis("off")

    plt.subplot(2, 3, 2)
    plt.imshow(overlay_cam1)
    plt.title(
        f"Stage 1 Grad-CAM\nPred: {binary_loaders['class_names'][stage1_pred]}\n"
        f"Prob: {stage1_probs[stage1_pred]:.3f}"
    )
    plt.axis("off")

    plt.subplot(2, 3, 3)
    plt.imshow(overlay_cam1_pp)
    plt.title("Stage 1 Grad-CAM++")
    plt.axis("off")

    if overlay_cam2 is not None:
        stage2_pred = int(np.argmax(stage2_probs))

        plt.subplot(2, 3, 5)
        plt.imshow(overlay_cam2)
        plt.title(
            f"Stage 2 Grad-CAM\nPred: {subtype_loaders['class_names'][stage2_pred]}\n"
            f"Prob: {stage2_probs[stage2_pred]:.3f}"
        )
        plt.axis("off")

        plt.subplot(2, 3, 6)
        plt.imshow(overlay_cam2_pp)
        plt.title("Stage 2 Grad-CAM++")
        plt.axis("off")
    else:
        plt.subplot(2, 3, 5)
        plt.text(0.5, 0.5, "Stage 2 skipped\nPrediction: NORMAL", ha="center", va="center", fontsize=14)
        plt.axis("off")

    plt.tight_layout()
    plt.show()

    return {
        "index": index,
        "true_label": idx_to_final_class[int(true_label)],
        "predicted_label": idx_to_final_class[pred_idx],
        "stage1_probs": stage1_probs,
        "stage2_probs": stage2_probs
    }


for _ in range(5):
    result = visualize_two_stage_explanation(three_class_test_dataset)
    print(result)