# -*- coding: utf-8 -*-
"""dino_medical_attention_threshold_tuned_complete_noLocalizationImprovement.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u5AnvYut_JB98yOd_wE-oVsqw8uYCeGS

**DINOv3 + Medical Attention Localization Module**


Two-Stage Pneumonia Classification using DINOv3 with Medical Attention Localization

Project Overview:
This notebook implements a two-stage deep learning pipeline
for chest X-ray classification using DINOv3 feature extraction
and attention-guided localization.

Stage 1:
NORMAL vs PNEUMONIA classification

Stage 2:
BACTERIAL vs VIRAL pneumonia subtype classification

Key Features:
- DINOv3 Vision Transformer backbone
- Threshold-tuned two-stage inference
- Medical attention localization module
- Attention heatmap visualization
- Explainability-driven predictions
- Three-class evaluation pipeline
- Confusion matrix and metric analysis

Dataset:
Chest X-ray Pneumonia Dataset

Final Classes:
NORMAL
BACTERIAL PNEUMONIA
VIRAL PNEUMONIA

Author:
Shivangi Mittal
"""

# Install dependencies because DINOv3 support needs a recent Transformers version.
!pip -q install -U "transformers>=4.56.0" accelerate timm

# Imports


import os
import random
import shutil
import math
import cv2
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torch.utils.data import DataLoader, random_split, Subset

from torchvision import datasets, transforms
from PIL import Image

from transformers import AutoImageProcessor, AutoModel

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report,
    balanced_accuracy_score
)

#Reproducibility and device


SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

# 4. Path to the dataset

from google.colab import drive
drive.mount('/content/drive')

ORIGINAL_DATA_DIR = "/content/drive/MyDrive/finalProject_682/chest_xray"

BINARY_DATA_DIR = "/content/chest_xray_binary"
SUBTYPE_DATA_DIR = "/content/chest_xray_subtype"
THREE_CLASS_DATA_DIR = "/content/chest_xray_3class"

DINO_MODEL_NAME = "facebook/dinov3-vitb16-pretrain-lvd1689m"
#DINO_MODEL_NAME = "facebook/dinov2-base"

IMG_SIZE = 224
BATCH_SIZE = 16
NUM_WORKERS = 2

# delete existing folders
import shutil
import os

for path in [BINARY_DATA_DIR, SUBTYPE_DATA_DIR, THREE_CLASS_DATA_DIR]:
    if os.path.exists(path):
        shutil.rmtree(path)
        print("Deleted:", path)

#Dataset creation

def safe_copy(src, dst):
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    shutil.copy2(src, dst)


def is_image_file(file_name):
    valid_extensions = (".jpg", ".jpeg", ".png", ".bmp", ".tif", ".tiff", ".webp")
    return file_name.lower().endswith(valid_extensions)


def create_two_stage_datasets(original_dir, binary_dir, subtype_dir, three_class_dir):

    if os.path.exists(binary_dir) and os.path.exists(subtype_dir) and os.path.exists(three_class_dir):
        print("Datasets already exist. Skipping dataset creation.")
        return

    for split in ["train", "val", "test"]:
        original_split_dir = os.path.join(original_dir, split)
        normal_dir = os.path.join(original_split_dir, "NORMAL")
        pneumonia_dir = os.path.join(original_split_dir, "PNEUMONIA")

        for base_dir, classes in [
            (binary_dir, ["NORMAL", "PNEUMONIA"]),
            (subtype_dir, ["BACTERIAL", "VIRAL"]),
            (three_class_dir, ["NORMAL", "BACTERIAL", "VIRAL"]),
        ]:
            for cls in classes:
                os.makedirs(os.path.join(base_dir, split, cls), exist_ok=True)

        if os.path.exists(normal_dir):
            for file_name in os.listdir(normal_dir):
                if not is_image_file(file_name):
                    continue
                src = os.path.join(normal_dir, file_name)
                if not os.path.isfile(src):
                    continue
                safe_copy(src, os.path.join(binary_dir, split, "NORMAL", file_name))
                safe_copy(src, os.path.join(three_class_dir, split, "NORMAL", file_name))

        if os.path.exists(pneumonia_dir):
            for file_name in os.listdir(pneumonia_dir):
                if not is_image_file(file_name):
                    continue
                src = os.path.join(pneumonia_dir, file_name)
                if not os.path.isfile(src):
                    continue

                lower_name = file_name.lower()
                safe_copy(src, os.path.join(binary_dir, split, "PNEUMONIA", file_name))

                if "bacteria" in lower_name:
                    safe_copy(src, os.path.join(subtype_dir, split, "BACTERIAL", file_name))
                    safe_copy(src, os.path.join(three_class_dir, split, "BACTERIAL", file_name))
                elif "virus" in lower_name:
                    safe_copy(src, os.path.join(subtype_dir, split, "VIRAL", file_name))
                    safe_copy(src, os.path.join(three_class_dir, split, "VIRAL", file_name))
                else:
                    print("Skipped unknown pneumonia subtype:", file_name)

    print("Created all datasets.")


def print_folder_counts(data_dir, classes):
    print(f"\nDataset: {data_dir}")

    for split in ["train", "val", "test"]:
        print(f"\n{split.upper()}")

        for cls in classes:
            folder = os.path.join(data_dir, split, cls)
            count = len(os.listdir(folder)) if os.path.exists(folder) else 0
            print(f"{cls}: {count}")


create_two_stage_datasets(
    ORIGINAL_DATA_DIR,
    BINARY_DATA_DIR,
    SUBTYPE_DATA_DIR,
    THREE_CLASS_DATA_DIR
)

print_folder_counts(BINARY_DATA_DIR, ["NORMAL", "PNEUMONIA"])
print_folder_counts(SUBTYPE_DATA_DIR, ["BACTERIAL", "VIRAL"])
print_folder_counts(THREE_CLASS_DATA_DIR, ["NORMAL", "BACTERIAL", "VIRAL"])

# DINO-compatible transforms

from huggingface_hub import login

login()

processor = AutoImageProcessor.from_pretrained(DINO_MODEL_NAME)

image_mean = processor.image_mean if hasattr(processor, "image_mean") else [0.485, 0.456, 0.406]
image_std = processor.image_std if hasattr(processor, "image_std") else [0.229, 0.224, 0.225]

train_transforms = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.RandomHorizontalFlip(p=0.3),
    transforms.RandomRotation(5),
    transforms.ToTensor(),
    transforms.Normalize(mean=image_mean, std=image_std),
])

val_test_transforms = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(mean=image_mean, std=image_std),
])

print("Using backbone:", DINO_MODEL_NAME)
print("DINO mean:", image_mean)
print("DINO std:", image_std)

#Dataset loader


def make_loaders(data_dir, batch_size=16, use_train_split_for_validation=True):
    train_dir = os.path.join(data_dir, "train")
    val_dir = os.path.join(data_dir, "val")
    test_dir = os.path.join(data_dir, "test")

    train_full_aug = datasets.ImageFolder(train_dir, transform=train_transforms)
    train_full_plain = datasets.ImageFolder(train_dir, transform=val_test_transforms)
    class_names = train_full_aug.classes

    if use_train_split_for_validation:
        val_size = int(0.15 * len(train_full_aug))
        train_size = len(train_full_aug) - val_size

        generator = torch.Generator().manual_seed(SEED)
        all_indices = torch.randperm(len(train_full_aug), generator=generator).tolist()
        train_indices = all_indices[:train_size]
        val_indices = all_indices[train_size:]

        train_dataset = Subset(train_full_aug, train_indices)
        val_dataset = Subset(train_full_plain, val_indices)

        train_targets_for_weights = np.array([train_full_aug.targets[i] for i in train_indices])
    else:
        train_dataset = train_full_aug
        val_dataset = datasets.ImageFolder(val_dir, transform=val_test_transforms)
        train_targets_for_weights = np.array(train_full_aug.targets)

    test_dataset = datasets.ImageFolder(test_dir, transform=val_test_transforms)

    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=NUM_WORKERS, pin_memory=True)
    val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False, num_workers=NUM_WORKERS, pin_memory=True)
    test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False, num_workers=NUM_WORKERS, pin_memory=True)

    num_classes = len(class_names)
    class_counts = np.bincount(train_targets_for_weights, minlength=num_classes)
    class_counts_safe = np.where(class_counts == 0, 1, class_counts)

    class_weights = 1.0 / torch.tensor(class_counts_safe, dtype=torch.float)
    class_weights = class_weights / class_weights.sum()
    class_weights = class_weights.to(device)

    class_to_idx = datasets.ImageFolder(train_dir).class_to_idx

    print("\nLoaded:", data_dir)
    print("Classes:", class_names)
    print("Class to index:", class_to_idx)
    print("Class counts used for weights:", dict(zip(class_names, class_counts)))
    print("Class weights:", class_weights)
    print("Train size:", len(train_dataset))
    print("Val size:", len(val_dataset))
    print("Test size:", len(test_dataset))

    return {
        "train_loader": train_loader,
        "val_loader": val_loader,
        "test_loader": test_loader,
        "train_dataset": train_dataset,
        "val_dataset": val_dataset,
        "test_dataset": test_dataset,
        "class_names": class_names,
        "class_weights": class_weights,
        "num_classes": num_classes,
        "class_to_idx": class_to_idx,
    }

#Medical Attention Localization Module

class MedicalAttentionLocalizationModule(nn.Module):
    """
    This is the new contribution.

    DINOv3 gives patch tokens.
    This module learns which patch tokens are medically important.
    It also adds a soft lung-shaped prior so attention is encouraged toward lung regions.
    """

    def __init__(self, hidden_dim, prior_strength=1.0):
        super().__init__()
        self.prior_strength = prior_strength

        self.attention_mlp = nn.Sequential(
            nn.LayerNorm(hidden_dim),
            nn.Linear(hidden_dim, hidden_dim // 2),
            nn.GELU(),
            nn.Linear(hidden_dim // 2, 1),
        )

    def build_lung_prior(self, grid_h, grid_w, device):
        y = torch.linspace(-1.0, 1.0, grid_h, device=device)
        x = torch.linspace(-1.0, 1.0, grid_w, device=device)
        yy, xx = torch.meshgrid(y, x, indexing="ij")

        left_lung = (((xx + 0.35) / 0.38) ** 2 + ((yy + 0.02) / 0.78) ** 2) <= 1.0
        right_lung = (((xx - 0.35) / 0.38) ** 2 + ((yy + 0.02) / 0.78) ** 2) <= 1.0
        lung_mask = (left_lung | right_lung).float()

        lung_mask = lung_mask + 0.15
        lung_mask = lung_mask / lung_mask.max()
        return lung_mask.reshape(1, grid_h * grid_w, 1)

    def forward(self, patch_tokens):
        batch_size, num_patches, hidden_dim = patch_tokens.shape

        grid_size = int(math.sqrt(num_patches))
        if grid_size * grid_size != num_patches:
            learned_logits = self.attention_mlp(patch_tokens)
            attention_weights = torch.softmax(learned_logits, dim=1)
            localized_embedding = torch.sum(attention_weights * patch_tokens, dim=1)
            return localized_embedding, attention_weights.squeeze(-1), None

        learned_logits = self.attention_mlp(patch_tokens)
        lung_prior = self.build_lung_prior(grid_size, grid_size, patch_tokens.device)

        attention_logits = learned_logits + self.prior_strength * lung_prior
        attention_weights = torch.softmax(attention_logits, dim=1)

        localized_embedding = torch.sum(attention_weights * patch_tokens, dim=1)
        attention_map = attention_weights.reshape(batch_size, grid_size, grid_size)

        return localized_embedding, attention_weights.squeeze(-1), attention_map

#DINO classifier with custom medical attention module

class DINOv3MedicalAttentionClassifier(nn.Module):
    def __init__(self, model_name, num_classes, dropout=0.3, prior_strength=1.0):
        super().__init__()

        self.backbone = AutoModel.from_pretrained(model_name)
        hidden_dim = self.backbone.config.hidden_size

        self.medical_attention = MedicalAttentionLocalizationModule(
            hidden_dim=hidden_dim,
            prior_strength=prior_strength
        )

        self.classifier = nn.Sequential(
            nn.LayerNorm(hidden_dim * 2),
            nn.Linear(hidden_dim * 2, 512),
            nn.GELU(),
            nn.Dropout(dropout),
            nn.Linear(512, num_classes)
        )

    def forward(self, pixel_values, return_attention=False):
        outputs = self.backbone(pixel_values=pixel_values)
        tokens = outputs.last_hidden_state

        cls_token = tokens[:, 0, :]
        patch_tokens = tokens[:, 1:, :]

        localized_embedding, attention_weights, attention_map = self.medical_attention(patch_tokens)
        fused_embedding = torch.cat([cls_token, localized_embedding], dim=1)
        logits = self.classifier(fused_embedding)

        if return_attention:
            return logits, attention_map, attention_weights
        return logits

#Training helpers

def freeze_backbone(model):
    for param in model.backbone.parameters():
        param.requires_grad = False


def unfreeze_backbone(model):
    for param in model.backbone.parameters():
        param.requires_grad = True


def train_one_epoch(model, loader, criterion, optimizer, device):
    model.train()
    running_loss = 0.0
    all_preds = []
    all_labels = []

    for images, labels in loader:
        images = images.to(device, non_blocking=True)
        labels = labels.to(device, non_blocking=True)

        optimizer.zero_grad()
        logits = model(images)
        loss = criterion(logits, labels)
        loss.backward()
        optimizer.step()

        running_loss += loss.item() * images.size(0)
        preds = torch.argmax(logits, dim=1)
        all_preds.extend(preds.detach().cpu().numpy())
        all_labels.extend(labels.detach().cpu().numpy())

    epoch_loss = running_loss / len(loader.dataset)
    epoch_acc = accuracy_score(all_labels, all_preds)
    return epoch_loss, epoch_acc


def evaluate(model, loader, criterion, device, threshold=None, positive_class_idx=1):
    model.eval()
    running_loss = 0.0
    all_preds = []
    all_labels = []
    all_probs = []

    with torch.no_grad():
        for images, labels in loader:
            images = images.to(device, non_blocking=True)
            labels = labels.to(device, non_blocking=True)

            logits = model(images)
            loss = criterion(logits, labels)
            probs = torch.softmax(logits, dim=1)

            if threshold is not None:
                positive_probs = probs[:, positive_class_idx]
                preds = (positive_probs >= threshold).long()
            else:
                preds = torch.argmax(probs, dim=1)

            running_loss += loss.item() * images.size(0)
            all_preds.extend(preds.detach().cpu().numpy())
            all_labels.extend(labels.detach().cpu().numpy())
            all_probs.extend(probs.detach().cpu().numpy())

    epoch_loss = running_loss / len(loader.dataset)
    epoch_acc = accuracy_score(all_labels, all_preds)
    return epoch_loss, epoch_acc, np.array(all_labels), np.array(all_preds), np.array(all_probs)


def train_model_phase(model, loaders, optimizer, phase_name, best_path, epochs=5, patience=3):
    # Small label smoothing reduces overconfidence and can reduce false pneumonia predictions.
    criterion = nn.CrossEntropyLoss(weight=loaders["class_weights"], label_smoothing=0.05)
    best_val_loss = float("inf")
    patience_counter = 0
    history = []

    for epoch in range(1, epochs + 1):
        train_loss, train_acc = train_one_epoch(
            model, loaders["train_loader"], criterion, optimizer, device
        )
        val_loss, val_acc, _, _, _ = evaluate(
            model, loaders["val_loader"], criterion, device
        )

        history.append({
            "epoch": epoch,
            "train_loss": train_loss,
            "train_acc": train_acc,
            "val_loss": val_loss,
            "val_acc": val_acc,
        })

        print(
            f"{phase_name} | Epoch {epoch}/{epochs} | "
            f"Train Loss: {train_loss:.4f} | Train Acc: {train_acc:.4f} | "
            f"Val Loss: {val_loss:.4f} | Val Acc: {val_acc:.4f}"
        )

        if val_loss < best_val_loss:
            best_val_loss = val_loss
            patience_counter = 0
            torch.save(model.state_dict(), best_path)
            print("Saved best model:", best_path)
        else:
            patience_counter += 1
            if patience_counter >= patience:
                print("Early stopping.")
                break

    model.load_state_dict(torch.load(best_path, map_location=device))
    return history


def train_staged_dinov3(loaders, model_name, frozen_epochs=5, finetune_epochs=5):
    model = DINOv3MedicalAttentionClassifier(
        model_name=DINO_MODEL_NAME,
        num_classes=loaders["num_classes"],
        dropout=0.4,
        prior_strength=0.5
    ).to(device)

    frozen_path = f"{model_name}_dino_attention_frozen_best.pth"
    finetune_path = f"{model_name}_dino_attention_finetuned_best.pth"

    print("Phase 1: Frozen DINO backbone. Training classifier + medical attention only.")
    freeze_backbone(model)
    optimizer = optim.AdamW(
        list(model.medical_attention.parameters()) + list(model.classifier.parameters()),
        lr=1e-4,
        weight_decay=1e-4
    )
    history_1 = train_model_phase(
        model, loaders, optimizer,
        phase_name=f"{model_name} Frozen",
        best_path=frozen_path,
        epochs=frozen_epochs,
        patience=3
    )

    print("Phase 2: Fine-tuning full model with small learning rate.")
    unfreeze_backbone(model)
    optimizer = optim.AdamW([
        {"params": model.backbone.parameters(), "lr": 5e-7},
        {"params": model.medical_attention.parameters(), "lr": 3e-5},
        {"params": model.classifier.parameters(), "lr": 3e-5},
    ], weight_decay=1e-4)

    history_2 = train_model_phase(
        model, loaders, optimizer,
        phase_name=f"{model_name} Finetune",
        best_path=finetune_path,
        epochs=finetune_epochs,
        patience=3
    )

    return model, frozen_path, finetune_path, history_1, history_2


def evaluate_and_print(model, loaders, title, threshold=None, positive_class_idx=1):
    criterion = nn.CrossEntropyLoss(weight=loaders["class_weights"])
    test_loss, test_acc, y_true, y_pred, y_probs = evaluate(
        model,
        loaders["test_loader"],
        criterion,
        device,
        threshold=threshold,
        positive_class_idx=positive_class_idx
    )

    print("\n" + "=" * 60)
    print(title)
    print("=" * 60)
    print("Test Loss:", round(test_loss, 4))
    print("Test Accuracy:", round(test_acc, 4))
    print("Balanced Accuracy:", round(balanced_accuracy_score(y_true, y_pred), 4))
    print("Precision:", round(precision_score(y_true, y_pred, average="weighted", zero_division=0), 4))
    print("Recall:", round(recall_score(y_true, y_pred, average="weighted", zero_division=0), 4))
    print("F1:", round(f1_score(y_true, y_pred, average="weighted", zero_division=0), 4))
    print("Classification Report:")
    print(classification_report(y_true, y_pred, target_names=loaders["class_names"], zero_division=0))
    print("Confusion Matrix:", confusion_matrix(y_true, y_pred))

    return y_true, y_pred, y_probs


def tune_binary_threshold(model, loaders, thresholds=None, positive_class_name="PNEUMONIA", split="val_loader"):
    if thresholds is None:
        thresholds = [0.50, 0.55, 0.60, 0.65, 0.70, 0.75, 0.80, 0.85]

    criterion = nn.CrossEntropyLoss(weight=loaders["class_weights"])
    positive_class_idx = loaders["class_to_idx"][positive_class_name]
    normal_idx = loaders["class_to_idx"].get("NORMAL", 0)

    rows = []
    for threshold in thresholds:
        loss, acc, y_true, y_pred, y_probs = evaluate(
            model,
            loaders[split],
            criterion,
            device,
            threshold=threshold,
            positive_class_idx=positive_class_idx
        )

        rows.append({
            "threshold": threshold,
            "loss": loss,
            "accuracy": accuracy_score(y_true, y_pred),
            "balanced_accuracy": balanced_accuracy_score(y_true, y_pred),
            "macro_f1": f1_score(y_true, y_pred, average="macro", zero_division=0),
            "weighted_f1": f1_score(y_true, y_pred, average="weighted", zero_division=0),
            "normal_recall": recall_score(y_true, y_pred, labels=[normal_idx], average="macro", zero_division=0),
            "pneumonia_recall": recall_score(y_true, y_pred, labels=[positive_class_idx], average="macro", zero_division=0),
        })

    threshold_df = pd.DataFrame(rows)
    print("\nStage 1 threshold tuning results on", split)
    print(threshold_df)

    best_row = threshold_df.sort_values("macro_f1", ascending=False).iloc[0]
    best_threshold = float(best_row["threshold"])
    print("Best Stage 1 threshold by macro F1:", best_threshold)

    return best_threshold, threshold_df

#Train Stage 1: NORMAL vs PNEUMONIA

binary_loaders = make_loaders(
    BINARY_DATA_DIR,
    batch_size=BATCH_SIZE,
    use_train_split_for_validation=True
)

stage1_net, stage1_frozen_path, stage1_finetune_path, stage1_history_1, stage1_history_2 = train_staged_dinov3(
    binary_loaders,
    model_name="stage1_normal_vs_pneumonia",
    frozen_epochs=5,
    finetune_epochs=5
)

BEST_STAGE1_THRESHOLD, stage1_threshold_df = tune_binary_threshold(
    stage1_net,
    binary_loaders,
    thresholds=[0.50, 0.55, 0.60, 0.65, 0.70, 0.75, 0.80, 0.85],
    positive_class_name="PNEUMONIA",
    split="val_loader"
)

pneumonia_idx = binary_loaders["class_to_idx"]["PNEUMONIA"]

s1_true, s1_pred, s1_probs = evaluate_and_print(
    stage1_net,
    binary_loaders,
    title=f"Stage 1: DINO + Medical Attention | NORMAL vs PNEUMONIA | threshold=0.85",
    threshold=BEST_STAGE1_THRESHOLD,
    positive_class_idx=pneumonia_idx
)

#Train Stage 2: BACTERIAL vs VIRAL

subtype_loaders = make_loaders(
    SUBTYPE_DATA_DIR,
    batch_size=BATCH_SIZE,
    use_train_split_for_validation=True
)

stage2_net, stage2_frozen_path, stage2_finetune_path, stage2_history_1, stage2_history_2 = train_staged_dinov3(
    subtype_loaders,
    model_name="stage2_bacterial_vs_viral",
    frozen_epochs=5,
    finetune_epochs=5
)

s2_true, s2_pred, s2_probs = evaluate_and_print(
    stage2_net,
    subtype_loaders,
    title="Stage 2: DINO + Medical Attention | BACTERIAL vs VIRAL"
)

#Final two-stage evaluation on 3-class test set

three_class_test_dataset = datasets.ImageFolder(
    os.path.join(THREE_CLASS_DATA_DIR, "test"),
    transform=val_test_transforms
)

three_class_test_loader = DataLoader(
    three_class_test_dataset,
    batch_size=1,
    shuffle=False,
    num_workers=NUM_WORKERS
)

final_class_to_idx = three_class_test_dataset.class_to_idx
final_idx_to_class = {v: k for k, v in final_class_to_idx.items()}

binary_idx_to_class = {v: k for k, v in binary_loaders["class_to_idx"].items()}
subtype_idx_to_class = {v: k for k, v in subtype_loaders["class_to_idx"].items()}

print("Final 3-class mapping:", final_class_to_idx)
print("Stage 1 mapping:", binary_loaders["class_to_idx"])
print("Stage 2 mapping:", subtype_loaders["class_to_idx"])


def two_stage_predict(image_tensor, pneumonia_threshold=0.50):
    stage1_net.eval()
    stage2_net.eval()

    image_tensor = image_tensor.to(device)

    with torch.no_grad():
        stage1_logits = stage1_net(image_tensor)
        stage1_probs = torch.softmax(stage1_logits, dim=1)[0]

        pneumonia_idx = binary_loaders["class_to_idx"]["PNEUMONIA"]
        pneumonia_prob = stage1_probs[pneumonia_idx].item()

        if pneumonia_prob < pneumonia_threshold:
            return "NORMAL", pneumonia_prob, None

        stage2_logits = stage2_net(image_tensor)
        stage2_probs = torch.softmax(stage2_logits, dim=1)[0]
        stage2_pred_idx = torch.argmax(stage2_probs).item()
        subtype_name = subtype_idx_to_class[stage2_pred_idx]
        subtype_prob = stage2_probs[stage2_pred_idx].item()

        return subtype_name, pneumonia_prob, subtype_prob


def evaluate_two_stage_with_threshold(threshold=0.50):
    final_true = []
    final_pred = []
    final_records = []

    for image, label in three_class_test_loader:
        true_name = final_idx_to_class[label.item()]
        pred_name, pneumonia_prob, subtype_prob = two_stage_predict(
            image,
            pneumonia_threshold=threshold
        )

        final_true.append(true_name)
        final_pred.append(pred_name)
        final_records.append({
            "true": true_name,
            "pred": pred_name,
            "pneumonia_prob": pneumonia_prob,
            "subtype_prob": subtype_prob,
        })

    labels = ["NORMAL", "BACTERIAL", "VIRAL"]

    print("\n" + "=" * 60)
    print(f"Final Two-Stage Evaluation | Threshold = {threshold}")
    print("=" * 60)
    print("Accuracy:", round(accuracy_score(final_true, final_pred), 4))
    print("Balanced Accuracy:", round(balanced_accuracy_score(final_true, final_pred), 4))
    print("Precision:", round(precision_score(final_true, final_pred, average="weighted", zero_division=0), 4))
    print("Recall:", round(recall_score(final_true, final_pred, average="weighted", zero_division=0), 4))
    print("F1:", round(f1_score(final_true, final_pred, average="weighted", zero_division=0), 4))
    print("\nClassification Report:\n")
    print(classification_report(final_true, final_pred, labels=labels, zero_division=0))
    print("Confusion Matrix:\n", confusion_matrix(final_true, final_pred, labels=labels))

    return final_true, final_pred, final_records
final_true, final_pred, final_records = evaluate_two_stage_with_threshold(threshold=0.85)

# Optional final threshold sweep on the 3-class test set

threshold_results = []

for threshold in [0.50, 0.55, 0.60, 0.65, 0.70, 0.75, 0.80, 0.85]:
    y_true, y_pred, _ = evaluate_two_stage_with_threshold(threshold=threshold)
    threshold_results.append({
        "threshold": threshold,
        "accuracy": accuracy_score(y_true, y_pred),
        "balanced_accuracy": balanced_accuracy_score(y_true, y_pred),
        "precision": precision_score(y_true, y_pred, average="weighted", zero_division=0),
        "recall": recall_score(y_true, y_pred, average="weighted", zero_division=0),
        "f1": f1_score(y_true, y_pred, average="weighted", zero_division=0),
    })

threshold_df = pd.DataFrame(threshold_results)
print(threshold_df)

best_row = threshold_df.sort_values("f1", ascending=False).iloc[0]
BEST_FINAL_TEST_THRESHOLD = float(best_row["threshold"])
print("Best final test threshold by weighted F1:", BEST_FINAL_TEST_THRESHOLD)

final_true_best_test, final_pred_best_test, final_records_best_test = evaluate_two_stage_with_threshold(
    threshold=0.85
)

#Visualize medical attention map

inv_mean = np.array(image_mean)
inv_std = np.array(image_std)


def denormalize_image(tensor_img):
    img = tensor_img.detach().cpu().numpy().transpose(1, 2, 0)
    img = img * inv_std + inv_mean
    img = np.clip(img, 0, 1)
    return img


def overlay_attention(original_img, attention_map, alpha=0.45):
    heatmap = attention_map.detach().cpu().numpy()
    heatmap = cv2.resize(heatmap, (original_img.shape[1], original_img.shape[0]))
    heatmap = (heatmap - heatmap.min()) / (heatmap.max() - heatmap.min() + 1e-8)
    heatmap_uint8 = np.uint8(255 * heatmap)
    heatmap_color = cv2.applyColorMap(heatmap_uint8, cv2.COLORMAP_JET)
    heatmap_color = cv2.cvtColor(heatmap_color, cv2.COLOR_BGR2RGB) / 255.0
    overlay = (1 - alpha) * original_img + alpha * heatmap_color
    overlay = np.clip(overlay, 0, 1)
    return overlay, heatmap


def visualize_two_stage_attention(dataset, index=None, threshold=None):
    if threshold is None:
        threshold = BEST_STAGE1_THRESHOLD

    if index is None:
        index = random.randint(0, len(dataset) - 1)

    image_tensor, label = dataset[index]
    true_name = final_idx_to_class[label]
    input_tensor = image_tensor.unsqueeze(0).to(device)

    stage1_net.eval()
    stage2_net.eval()

    with torch.no_grad():
        stage1_logits, stage1_attention_map, _ = stage1_net(input_tensor, return_attention=True)
        stage1_probs = torch.softmax(stage1_logits, dim=1)[0]
        pneumonia_idx = binary_loaders["class_to_idx"]["PNEUMONIA"]
        pneumonia_prob = stage1_probs[pneumonia_idx].item()

        if pneumonia_prob < threshold:
            pred_name = "NORMAL"
            used_model_name = "Stage 1: NORMAL vs PNEUMONIA"
            attention_map = stage1_attention_map[0]
        else:
            stage2_logits, stage2_attention_map, stage2_attention_weights = stage2_net(input_tensor, return_attention=True)
            stage2_probs = torch.softmax(stage2_logits, dim=1)[0]
            stage2_pred_idx = torch.argmax(stage2_probs).item()
            pred_name = subtype_idx_to_class[stage2_pred_idx]
            used_model_name = "Stage 2: BACTERIAL vs VIRAL"
            if stage2_attention_map is not None:
                attention_map = stage2_attention_map[0]
            else:
                num_patches = stage2_attention_weights.shape[1]
                grid_size = int(math.sqrt(num_patches))
                usable_patches = grid_size * grid_size
                attention_map = stage2_attention_weights[0][:usable_patches].reshape(grid_size, grid_size)

    original_img = denormalize_image(image_tensor)
    overlay, heatmap = overlay_attention(original_img, attention_map)

    plt.figure(figsize=(15, 5))

    plt.subplot(1, 3, 1)
    plt.imshow(original_img)
    plt.title(f"Original\nTrue: {true_name}")
    plt.axis("off")

    plt.subplot(1, 3, 2)
    plt.imshow(heatmap, cmap="jet")
    plt.title("Medical Attention Map")
    plt.axis("off")

    plt.subplot(1, 3, 3)
    plt.imshow(overlay)
    plt.title(f"Overlay\nPred: {pred_name}\n{used_model_name}")
    plt.axis("off")

    plt.tight_layout()
    plt.show()


visualize_two_stage_attention(three_class_test_dataset, threshold=0.85)

#Saving models to Google Drive

SAVE_DIR = "/content/drive/MyDrive/finalProject_682/dino_medical_attention_models"
os.makedirs(SAVE_DIR, exist_ok=True)

shutil.copy(stage1_finetune_path, os.path.join(SAVE_DIR, stage1_finetune_path))
shutil.copy(stage2_finetune_path, os.path.join(SAVE_DIR, stage2_finetune_path))

print("Saved models to:", SAVE_DIR)